// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDisable(arg1) {
  return window['go']['main']['App']['BackupDisable'](arg1);
}

export function BackupEnable(arg1, arg2, arg3) {
  return window['go']['main']['App']['BackupEnable'](arg1, arg2, arg3);
}

export function BackupListEnabled() {
  return window['go']['main']['App']['BackupListEnabled']();
}

export function BackupNow(arg1) {
  return window['go']['main']['App']['BackupNow'](arg1);
}

export function BackupPull(arg1, arg2) {
  return window['go']['main']['App']['BackupPull'](arg1, arg2);
}

export function BackupStatus(arg1) {
  return window['go']['main']['App']['BackupStatus'](arg1);
}

export function ClearAuthToken() {
  return window['go']['main']['App']['ClearAuthToken']();
}

export function ClearAuthTokenLocal() {
  return window['go']['main']['App']['ClearAuthTokenLocal']();
}

export function Context() {
  return window['go']['main']['App']['Context']();
}

export function DropboxConnect() {
  return window['go']['main']['App']['DropboxConnect']();
}

export function DropboxDisconnect() {
  return window['go']['main']['App']['DropboxDisconnect']();
}

export function DropboxExport(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropboxExport'](arg1, arg2, arg3);
}

export function DropboxImport(arg1, arg2) {
  return window['go']['main']['App']['DropboxImport'](arg1, arg2);
}

export function DropboxList(arg1) {
  return window['go']['main']['App']['DropboxList'](arg1);
}

export function DropboxStatus() {
  return window['go']['main']['App']['DropboxStatus']();
}

export function GetAuthToken() {
  return window['go']['main']['App']['GetAuthToken']();
}

export function GetLastEmail() {
  return window['go']['main']['App']['GetLastEmail']();
}

export function GetMediaURL() {
  return window['go']['main']['App']['GetMediaURL']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LogJS(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogJS'](arg1, arg2, arg3);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function PickFolder(arg1, arg2) {
  return window['go']['main']['App']['PickFolder'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['main']['App']['RequestQuit']();
}

export function SetLastEmail(arg1) {
  return window['go']['main']['App']['SetLastEmail'](arg1);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
