// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function BackupDisable(arg1:string):Promise<void>;

export function BackupEnable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BackupListEnabled():Promise<Array<string>>;

export function BackupNow(arg1:string):Promise<void>;

export function BackupPull(arg1:string,arg2:string):Promise<main.BackupPullResult>;

export function BackupStatus(arg1:string):Promise<main.BackupStatusInfo>;

export function ClearAuthToken():Promise<void>;

export function ClearAuthTokenLocal():Promise<void>;

export function Context():Promise<context.Context>;

export function DropboxConnect():Promise<main.DropboxAccount>;

export function DropboxDisconnect():Promise<void>;

export function DropboxExport(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function DropboxImport(arg1:string,arg2:Array<string>):Promise<void>;

export function DropboxList(arg1:string):Promise<Array<main.DropboxEntry>>;

export function DropboxStatus():Promise<main.DropboxAccount>;

export function GetAuthToken():Promise<string>;

export function GetLastEmail():Promise<string>;

export function GetMediaURL():Promise<string>;

export function HideWindow():Promise<void>;

export function LogJS(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function PickFolder(arg1:string,arg2:string):Promise<string>;

export function RequestQuit():Promise<void>;

export function SetLastEmail(arg1:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function SignIn():Promise<void>;

export function ToggleWindow():Promise<void>;
